sudo: false
language: go

before_install:
  - pushd $HOME
  - wget -nv https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.55.zip
  - unzip -q go_appengine_sdk_linux_amd64-1.9.55.zip
  - popd

install:
  # Fake app.yaml to force Go 1.8 as default is still 1.6
  - "echo -e 'runtime: go\napi_version: go1.8\nhandlers:\n- url: /.*\n  script: _go_app' > app.yaml"
  - $HOME/go_appengine/goapp get -t -v ./...
  - $HOME/go_appengine/goapp build -v ./...

script:
  - $HOME/go_appengine/goapp test -v ./...
  - go vet ./...
