sudo: false
language: go

go: "1.14"

before_install:
  - pushd $HOME
  - wget -nv https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.70.zip
  - unzip -q go_appengine_sdk_linux_amd64-1.9.70.zip
  - popd

install:
  # required by google.golang.org/grpc/internal/channelz/types_linux.go
  - $HOME/go_appengine/goapp get -t -v golang.org/x/sys/unix
  - $HOME/go_appengine/goapp get -t -v ./...
  - $HOME/go_appengine/goapp build -v ./...

script:
  - $HOME/go_appengine/goapp test -v ./...
  - go vet ./...
